config/routes.rb
Rails.application.routes.draw do
  root to: "application#welcome"
  
  get "about" => "application#about"
  
  resources :repositories

  resources :users do
    get 'search', on: :collection
  end
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/language_rank.rb
class LanguageRank < ActiveRecord::Base
  belongs_to :user
  validates :language, :score, :city_rank, :country_rank, :world_rank, :repository_count, :stars_count, presence: true
  validates :language, uniqueness: {scope: [:user_id, :city, :country]}
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  validates :name, presence: true, uniqueness: {scope: :user_id}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :language_ranks
  validates :login, presence: true, uniqueness: true
  
  def to_param
    login
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  caches_action :welcome
  
  def welcome
  end
  
  def about
  end
  
  def not_found
    raise ActiveRecord::RecordNotFound.new('Not Found')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  caches_action :index, :search, :show, :cache_path => Proc.new { |c| c.params }
  
  def index
    @user_list_presenter = UserListPresenter.new(params)
  end
  
  def search
    show_user(params[:login])
    rescue ActiveRecord::RecordNotFound => e
      redirect_to users_path, :alert => "User #{params[:login]} not found"
  end

  def show
    show_user(params[:id])
  end
  
  private 
  
  def show_user(login)
    @user = User.where(:login => login).first || not_found
    @language_ranks = @user.language_ranks
    render action: 'show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/about.html.erb
<div class="col-lg-12">
  <h1>About Github-awards</h1>
  
  <br>
  
  <p>I love feedback, if you have questions or comments send me a tweet : <a href="https://twitter.com/vdaubry">@vdaubry</a></p>
  <br>
  
  <h2>FAQ</h2>
  
  <div class="panel-group" id="accordion">
    <div class="faq_header">General questions</div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_who">Who am i ?</a>
        </h4>
      </div>
      <div id="collapse_who" class="panel-collapse collapse in">
        <div class="panel-body">
          I'm vincent daubry, i'm a Ruby developer living in Paris. You can find more about me and my project <a href="https://github.com/vdaubry">on github</a> 
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_contribute">I think this is fun, how can i help ?</a>
        </h4>
      </div>
      <div id="collapse_contribute" class="panel-collapse collapse">
        <div class="panel-body">
          There are many simple things that can greatly help this project :
          
          <ul>
            <li>
              Send a tweet supporting this project
            </li>
            <li>
              You probably are sitting next to another developer right now, tell him about Github-awards.
            </li>
            <li>
              If you want to contribute to the project, that's amazing ! Open an issue on Github and let's talk about it.
            </li>
          </ul>
          
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_privacy">What about privacy ?</a>
        </h4>
      </div>
      <div id="collapse_privacy" class="panel-collapse collapse">
        <div class="panel-body">
          I care a lot about this project not being creepy : it doesn't display your name or your email, you cannot search for someone by name or get access to their email. Only github username, avatar, repository list, location, and repositories language.
          
          Though we don't display it, the database might contains informations <strong>already publicly available</strong> on your Github profile :
          <ul>
            <li>
              email
            </li>
            <li>
              Full name
            </li>
            <li>
              Location
            </li>
            <li>
              Picture (avatar)
            </li>
            <li>
              Website or blog URL
            </li>
            <li>
              Company
            </li>
          </ul>
           
           If you want to edit or remove these informations you can reach me on twitter.
        </div>
      </div>
    </div>
    <div class="faq_header">Ranking questions</div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_rank">How do you calculate ranking ?</a>
        </h4>
      </div>
      <div id="collapse_rank" class="panel-collapse collapse">
        <div class="panel-body">
          First your score is computed for each language using this formula :
          <div class="">
            <pre>
              <code class="language-html" data-lang="html">sum(stars) + (1.0 - 1.0/count(repositories))</code>
            </pre>
          </div>
          
          <p>You are then ranked according to your score compared to other developers with repositories in the same languages, in the same location (by city, by country or worldwide).</p>
          
          <p>If you're interested in the ranking you should have a look at the SQL query that generates the ranking table : <a href="https://github.com/vdaubry/github-awards/blob/master/sql/rank.sql">rank.sql</a></p>
          
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_data">How did you get the data ?</a>
        </h4>
      </div>
      <div id="collapse_data" class="panel-collapse collapse">
        <div class="panel-body">
          Github-awards retrives data from 2 sources :
            <ul>
              <li>
                <a href="https://developer.github.com/v3/">Github API</a>
              </li>
              <li>
                <a href="https://www.githubarchive.org/">Github Archive</a>
              </li>
            </ul>
          
          For a detailed explanation of how the data were processed, see the project readme : <a href="https://github.com/vdaubry/github-awards">https://github.com/vdaubry/github-awards</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/welcome.html.erb
<div class="col-lg-12 intro">
  <form class="" action="<%= search_users_path %>" accept-charset="UTF-8" method="get">
    <div class="col-xs-6 col-centered text-center" style="top:200px">
      <div class="row">
        <div class="col-xs-12">
          <label>Discover your ranking on Github</label>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-xs-3"></div>
        <div class="col-xs-4">
          <input type="search" name="login" class="form-control" placeholder="Github username">
        </div>
        <div class="col-xs-2">
          <button type="submit" class="btn btn-default">Search</button>
        </div>
      </div>
    </div>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubAwards</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/cupertino/jquery-ui.min.css">
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.2/jquery-ui.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
    <!-- Google Analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-59714064-1', 'auto');
      ga('send', 'pageview');
    </script>
    
  </head>
  
  <body class="<%= "#{params[:controller]}_#{params[:action]}" %>">
    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button  type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'GitHub Awards', root_path, class: "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
              <form class="navbar-form navbar-left" action="<%= search_users_path %>" accept-charset="UTF-8" method="get">
                <input type="search" name="login" class="form-control" placeholder="Github username">
                <button type="submit" class="btn btn-default">Search</button>
              </form>
            </li>
            <li>
              <%= link_to 'Top users by city', users_path(:type => :city) %>
            </li>
            <li>
              <%= link_to 'Top users by country', users_path(:type => :country) %>
            </li>
            <li>
              <%= link_to 'Top users worldwide', users_path(:type => :world) %>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li><a href="/about">About</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <% if flash[:alert] %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <strong>Warning!</strong> <%= flash[:alert] %>
        </div>
      <% end %>
      
      <%= yield %>
      
    </div>
  </body>
  <hr>
  <footer>
    <p><strong>Think this project is fun ? Support it by sending a </strong> <a href="http://twitter.com/share?text=What's your ranking on Github ? Come check it out on Github-awards !&url=http://www.github-awards.com/&hashtags=github" title="Share github-awards on Twitter" target="_blank">tweet <i class="fa fa-twitter"></i></a></p>
    <p>Made by @vdaubry. See source on <a href="https://github.com/vdaubry/github-awards-api">GitHub</a></p>
  </footer>
</html>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Top <%= @user_list_presenter.language.capitalize %> Github developers <%= @user_list_presenter.title %></h1>
  </div>
</div>
<br>

<div class="row">
  <%= form_tag users_path, :method => 'get' do %>
    <%= hidden_field_tag(:type, @user_list_presenter.type) %>
    <div class="col-lg-2 col-xs-4">
      <%= select_tag :language, options_for_select(@user_list_presenter.languages, @user_list_presenter.language), :class => "form-control" %>
    </div>
    <% if @user_list_presenter.show_location_input %>
      <div class="col-lg-4 col-xs-4">
        <%= @user_list_presenter.location_input %>      
      </div>
    <% end %>
    <div class="col-lg-6 col-xs-4 pull-left">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  <% end %>
</div>
<br>

<div class="row">
  <div class="col-xs-12">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Username</th>
          <th><%= @user_list_presenter.rank_label %></th>
          <th>Stars</th>
        </tr>
      </thead>

      <tbody>
        <% @user_list_presenter.language_ranks.each do |language_rank| %>
          <tr>
            <td><%= link_to(image_tag(language_rank.user.gravatar_url, :class => "thumbnail avatar"), user_path(language_rank.user)) %></td>
            <td class="username"><%= link_to(language_rank.user.login, user_path(language_rank.user.login))%></td>
            <td><%= language_rank.city_rank %></td>
            <td><%= language_rank.stars_count %> <i class="fa fa-star star"></i></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <%= paginate @user_list_presenter.language_ranks %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag @user.gravatar_url, :class => "thumbnail avatar-bg"%>
    <h2><span class="mega-octicon octicon-mark-github"></span> <strong><%= link_to @user.login, "https://github.com/#{@user.login}" %></strong></h2>
    <p class="subtitle"><%= @user.city.try(:capitalize) %></p>
    <p class="subtitle"><%= @user.country.try(:capitalize) %></p>
  </div>
  <div class="col-md-9">
    <% if @language_ranks.empty? %>
      <div class="no-info">
        <p><strong>That's embarrassing...</strong></p>
        <p><strong>We don't have any info for your account. Maybe you don't have any repository on Github, or Github couldn't guess the language for any for your repos. </strong></p>
        <p>You can manually search for <%= link_to "top github developers in your city", users_path %> </p>
      </div>
    <% end %>
    
    <% @language_ranks.each do |language| %>
      <% presenter = LanguageRankPresenter.new(language) %>
      <div class="row">
        <div class="col-md-3">
          <p class="subtitle"><%= language.language.capitalize%> ranking</p>
        </div>
        <div class="col-md-9 pull-left">
          <% if @user.city && @user.country %>
            <table class="table rank">
              <tbody>
                <tr>
                  <td class="col-md-3"><%= link_to @user.city.capitalize, users_path(:language => language.language, :city => @user.city, :type => :city) %> :</td>
                  <td><%= presenter.city_rank.html_safe %> <i class="fa fa-trophy"></i></td>
                </tr>
                <tr>
                  <td class="col-md-3"><%= link_to @user.country.capitalize, users_path(:language => language.language, :country => @user.country, :type => :country) %> :</td>
                  <td><%= presenter.country_rank.html_safe %> <i class="fa fa-trophy"></i></td>
                </tr>
              </tbody>
            </table>
          <% else %>
            <p> We couldn't find your city or country from your location on github :( </p>
            <p>You can manually search for <%= link_to "top #{language.language.capitalize} github developers in your city", users_path(:language => language.language) %> </p>
          <% end %>
          <table class="table rank">
            <tbody>
              <tr>
                <td class="col-md-3"><%= link_to "Worldwilde", users_path(:language => language.language, :type => :world) %> :</td>
                <td><%= presenter.world_rank.html_safe %> <i class="fa fa-trophy"></i></td>
              </tr>
              <tr>
                <td class="col-md-3">Repos :</td>
                <td><%= language.repository_count %> <span class="octicon octicon-repo"></span></td>
              </tr>
              <tr>
                <td class="col-md-3">Stars :</td>
                <td><%= language.stars_count %> <span class="octicon octicon-star"></span></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <hr/>
    <% end %>
  </div>
</div>